services:
  - type: web
    name: django-todo-manager
    env: python
    buildCommand: "./build.sh"
    startCommand: "cd todo_manager && gunicorn todo_manager.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: "0"
      - key: PYTHON_VERSION
        value: "3.11.5"
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: "4"

  - type: pserv
    name: postgres-db
    env: postgresql
    plan: free
    databaseName: todo_manager_db
    databaseUser: todo_user
